<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert(
            [
                [
                    'title'=>'Зеленый чай',
                    'price'=>150,
                    'img'=>'media/images/products-seeder/green_tea.jpg',
                    'product_type'=>1,
                    'country'=>'Китай',
                    'flavor'=>'Цитрусовый',
                    'qty'=>150,
                    'created_at'=>'2023-10-15',
                    'rating'=>4,
                ],

                [
                    'title'=>'Черный чай',
                    'price'=>120,
                    'img'=>'media/images/products-seeder/black_tea.jpg',
                    'product_type'=>1,
                    'country'=>'Индия',
                    'flavor'=>'Классический',
                    'qty'=>180,
                    'created_at'=>'2023-09-20',
                    'rating'=>5,
                ],

                [
                    'title'=>'Оолонг',
                    'price'=>170,
                    'img'=>'media/images/products-seeder/oolong_tea.jpg',
                    'product_type'=>1,
                    'country'=>'Тайвань',
                    'flavor'=>'Цветочный',
                    'qty'=>130,
                    'created_at'=>'2023-08-05',
                    'rating'=>5,
                ],

                [
                    'title'=>'Ройбуш',
                    'price'=>130,
                    'img'=>'media/images/products-seeder/rooibos_tea.jpg',
                    'product_type'=>1,
                    'country'=>'Южная Африка',
                    'flavor'=>'Ягодный',
                    'qty'=>160,
                    'created_at'=>'2023-07-10',
                    'rating'=>4,
                ],

                [
                    'title'=>'Арабика',
                    'price'=>200,
                    'img'=>'media/images/products-seeder/arabica_coffee.jpeg',
                    'product_type'=>2,
                    'country'=>'Бразилия',
                    'flavor'=>'Средняя прожарка',
                    'qty'=>100,
                    'created_at'=>'2023-08-25',
                    'rating'=>4,
                ],

                [
                    'title'=>'Робуста',
                    'price'=>180,
                    'img'=>'media/images/products-seeder/robusta_coffee.jpeg',
                    'product_type'=>2,
                    'country'=>'Вьетнам',
                    'flavor'=>'Темная обжарка',
                    'qty'=>120,
                    'created_at'=>'2023-07-30',
                    'rating'=>5,
                ],

                [
                    'title'=>'Эспрессо',
                    'price'=>220,
                    'img'=>'media/images/products-seeder/espresso_coffee.jpeg',
                    'product_type'=>2,
                    'country'=>'Италия',
                    'flavor'=>'Средняя обжарка',
                    'qty'=>90,
                    'created_at'=>'2023-06-15',
                    'rating'=>5,
                ],

                [
                    'title'=>'Латте',
                    'price'=>190,
                    'img'=>'media/images/products-seeder/latte_coffee.png',
                    'product_type'=>2,
                    'country'=>'Италия',
                    'flavor'=>'Ванильный',
                    'qty'=>110,
                    'created_at'=>'2023-05-20',
                    'rating'=>4,
                ],

                [
                    'title'=>'Зеленый чай с жасмином',
                    'price'=>180,
                    'img'=>'media/images/products-seeder/jasmine_green_tea.jpeg',
                    'product_type'=>1,
                    'country'=>'Китай',
                    'flavor'=>'Цветочный',
                    'qty'=>120,
                    'created_at'=>'2023-04-25',
                    'rating'=>5,
                ],

                [
                    'title'=>'Пуэр',
                    'price'=>250,
                    'img'=>'media/images/products-seeder/puer_tea.jpg',
                    'product_type'=>1,
                    'country'=>'Китай',
                    'flavor'=>'Земляничный',
                    'qty'=>100,
                    'created_at'=>'2023-03-30',
                    'rating'=>5,
                ],

                [
                    'title'=>'Матча',
                    'price'=>300,
                    'img'=>'media/images/products-seeder/matcha_tea.jpg',
                    'product_type'=>1,
                    'country'=>'Япония',
                    'flavor'=>'Травяной',
                    'qty'=>80,
                    'created_at'=>'2023-02-05',
                    'rating'=>4,
                ],

                [
                    'title'=>'Каркаде',
                    'price'=>90,
                    'img'=>'media/images/products-seeder/hibiscus_tea.jpg',
                    'product_type'=>1,
                    'country'=>'Египет',
                    'flavor'=>'Ягодный',
                    'qty'=>140,
                    'created_at'=>'2023-01-10',
                    'rating'=>5,
                ],

                [
                    'title'=>'Колумбийский Сингл-Ориджин',
                    'price'=>280,
                    'img'=>'media/images/products-seeder/colombian_coffee.jpg',
                    'product_type'=>2,
                    'country'=>'Колумбия',
                    'flavor'=>'Средняя обжарка',
                    'qty'=>70,
                    'created_at'=>'2022-12-15',
                    'rating'=>4,
                ],

                [
                    'title'=>'Гватемальский Антигуа',
                    'price'=>260,
                    'img'=>'media/images/products-seeder/guatemalan_coffee.jpg',
                    'product_type'=>2,
                    'country'=>'Гватемала',
                    'flavor'=>'Средняя обжарка',
                    'qty'=>85,
                    'created_at'=>'2022-11-20',
                    'rating'=>4,
                ],

                [
                    'title'=>'Кенийская АА',
                    'price'=>320,
                    'img'=>'media/images/products-seeder/kenyan_coffee.jpg',
                    'product_type'=>2,
                    'country'=>'Кения',
                    'flavor'=>'Средняя обжарка',
                    'qty'=>60,
                    'created_at'=>'2022-10-25',
                    'rating'=>5,
                ],

                [
                    'title'=>'Мокка',
                    'price'=>230,
                    'img'=>'media/images/products-seeder/mocha_coffee.jpg',
                    'product_type'=>2,
                    'country'=>'Эфиопия',
                    'flavor'=>'Шоколадный',
                    'qty'=>95,
                    'created_at'=>'2022-09-30',
                    'rating'=>3,
                ],

                [
                    'title'=>'Ассамский чай',
                    'price'=>110,
                    'img'=>'media/images/products-seeder/assam_tea.jpg',
                    'product_type'=>1,
                    'country'=>'Индия',
                    'flavor'=>'Мальчишник',
                    'qty'=>160,
                    'created_at'=>'2022-08-05',
                    'rating'=>4,
                ],

                [
                    'title'=>'Дарджилинг',
                    'price'=>170,
                    'img'=>'media/images/products-seeder/darjeeling_tea.jpeg',
                    'product_type'=>1,
                    'country'=>'Индия',
                    'flavor'=>'Цветочный',
                    'qty'=>120,
                    'created_at'=>'2022-07-10',
                    'rating'=>2,
                ],

                [
                    'title'=>'Хойя ча',
                    'price'=>140,
                    'img'=>'media/images/products-seeder/hojicha_tea.jpg',
                    'product_type'=>1,
                    'country'=>'Япония',
                    'flavor'=>'Ореховый',
                    'qty'=>130,
                    'created_at'=>'2022-06-15',
                    'rating'=>3,
                ],

                [
                    'title'=>'Белый чай',
                    'price'=>190,
                    'img'=>'media/images/products-seeder/white_tea.jpeg',
                    'product_type'=>1,
                    'country'=>'Китай',
                    'flavor'=>'Фруктовый',
                    'qty'=>110,
                    'created_at'=>'2022-05-20',
                    'rating'=>4,
                ],

                [
                    'title'=>'Ямайская Голубая гора',
                    'price'=>350,
                    'img'=>'media/images/products-seeder/blue_mountain_coffee.jpeg',
                    'product_type'=>2,
                    'country'=>'Ямайка',
                    'flavor'=>'Средняя обжарка',
                    'qty'=>50,
                    'created_at'=>'2022-04-25',
                    'rating'=>5,
                ],

                [
                    'title'=>'Эфиопская Сидама',
                    'price'=>300,
                    'img'=>'media/images/products-seeder/sidamo_coffee.jpg',
                    'product_type'=>2,
                    'country'=>'Эфиопия',
                    'flavor'=>'Средняя обжарка',
                    'qty'=>70,
                    'created_at'=>'2022-03-30',
                    'rating'=>4,
                ],

                [
                    'title'=>'Коста-Риканский Тарразу',
                    'price'=>320,
                    'img'=>'media/images/products-seeder/tarrazu_coffee.jpg',
                    'product_type'=>2,
                    'country'=>'Коста-Рика',
                    'flavor'=>'Средняя обжарка',
                    'qty'=>65,
                    'created_at'=>'2022-02-05',
                    'rating'=>4,
                ],

                [
                    'title'=>'Гондурасский Ла-Паз',
                    'price'=>290,
                    'img'=>'media/images/products-seeder/la_paz_coffee.jpg',
                    'product_type'=>2,
                    'country'=>'Гондурас',
                    'flavor'=>'Средняя обжарка',
                    'qty'=>75,
                    'created_at'=>'2022-01-10',
                    'rating'=>5,
                ],

                [
                    'title'=>'Молочный улун',
                    'price'=>200,
                    'img'=>'media/images/products-seeder/milk_oolong_tea.jpg',
                    'product_type'=>1,
                    'country'=>'Тайвань',
                    'flavor'=>'Молочный',
                    'qty'=>90,
                    'created_at'=>'2022-12-01',
                    'rating'=>4,
                ],

                [
                    'title'=>'Розовый пуэр',
                    'price'=>250,
                    'img'=>'media/images/products-seeder/rose_puer_tea.jpg',
                    'product_type'=>1,
                    'country'=>'Китай',
                    'flavor'=>'Цветочный',
                    'qty'=>100,
                    'created_at'=>'2022-11-01',
                    'rating'=>4,
                ],

                [
                    'title'=>'Матча латте',
                    'price'=>180,
                    'img'=>'media/images/products-seeder/matcha_latte_tea.jpg',
                    'product_type'=>1,
                    'country'=>'Япония',
                    'flavor'=>'Молочный',
                    'qty'=>110,
                    'created_at'=>'2022-10-01',
                    'rating'=>4,
                ],

                [
                    'title'=>'Джинсенг чай',
                    'price'=>300,
                    'img'=>'media/images/products-seeder/ginseng_tea.jpeg',
                    'product_type'=>1,
                    'country'=>'Корея',
                    'flavor'=>'Тонизирующий',
                    'qty'=>80,
                    'created_at'=>'2022-09-01',
                    'rating'=>4,
                ],

                [
                    'title'=>'Кубинский Туркос',
                    'price'=>280,
                    'img'=>'media/images/products-seeder/turkos_coffee.jpeg',
                    'product_type'=>2,
                    'country'=>'Куба',
                    'flavor'=>'Темная обжарка',
                    'qty'=>90,
                    'created_at'=>'2022-08-01',
                    'rating'=>4,
                ],

                [
                    'title'=>'Мексиканская Чиапас',
                    'price'=>300,
                    'img'=>'media/images/products-seeder/chiapas_coffee.jpg',
                    'product_type'=>2,
                    'country'=>'Мексика',
                    'flavor'=>'Средняя обжарка',
                    'qty'=>80,
                    'created_at'=>'2022-07-01',
                    'rating'=>3,
                ],

                [
                    'title'=>'Перуанский Сантос',
                    'price'=>260,
                    'img'=>'media/images/products-seeder/santos_coffee.jpeg',
                    'product_type'=>2,
                    'country'=>'Перу',
                    'flavor'=>'Средняя обжарка',
                    'qty'=>100,
                    'created_at'=>'2022-06-01',
                    'rating'=>4,
                ],

                [
                    'title'=>'Индийский Малабар',
                    'price'=>320,
                    'img'=>'media/images/products-seeder/malabar_coffee.jpg',
                    'product_type'=>2,
                    'country'=>'Индия',
                    'flavor'=>'Темная обжарка',
                    'qty'=>70,
                    'created_at'=>'2022-05-01',
                    'rating'=>4,
                ],

                [
                    'title'=>'Сенча',
                    'price'=>120,
                    'img'=>'media/images/products-seeder/sencha_tea.jpg',
                    'product_type'=>1,
                    'country'=>'Япония',
                    'flavor'=>'Травяной',
                    'qty'=>130,
                    'created_at'=>'2022-04-01',
                    'rating'=>4,
                ],

                [
                    'title'=>'Жасминовый чай',
                    'price'=>150,
                    'img'=>'media/images/products-seeder/jasmine_tea.jpg',
                    'product_type'=>1,
                    'country'=>'Китай',
                    'flavor'=>'Цветочный',
                    'qty'=>140,
                    'created_at'=>'2022-03-01',
                    'rating'=>3,
                ],

                [
                    'title'=>'Песочный чай',
                    'price'=>110,
                    'img'=>'media/images/products-seeder/sandy_tea.jpg',
                    'product_type'=>1,
                    'country'=>'Япония',
                    'flavor'=>'Морской',
                    'qty'=>120,
                    'created_at'=>'2022-02-01',
                    'rating'=>4,
                ],

                [
                    'title'=>'Мате',
                    'price'=>130,
                    'img'=>'media/images/products-seeder/yerba_mate_tea.jpg',
                    'product_type'=>1,
                    'country'=>'Аргентина',
                    'flavor'=>'Травяной',
                    'qty'=>110,
                    'created_at'=>'2022-01-01',
                    'rating'=>4,
                ],

                [
                    'title'=>'Панама Геша',
                    'price'=>500,
                    'img'=>'media/images/products-seeder/gesha_coffee.jpeg',
                    'product_type'=>2,
                    'country'=>'Панама',
                    'flavor'=>'Средняя обжарка',
                    'qty'=>60,
                    'created_at'=>'2021-12-01',
                    'rating'=>5,
                ],

                [
                    'title'=>'Бурундийский Бурец',
                    'price'=>400,
                    'img'=>'media/images/products-seeder/burundi_buret_coffee.jpg',
                    'product_type'=>2,
                    'country'=>'Бурунди',
                    'flavor'=>'Средняя обжарка',
                    'qty'=>70,
                    'created_at'=>'2021-11-01',
                    'rating'=>4,
                ],

                [
                    'title'=>'Танзанийская Пеаберри',
                    'price'=>380,
                    'img'=>'media/images/products-seeder/tanzania_peaberry_coffee.jpg',
                    'product_type'=>2,
                    'country'=>'Танзания',
                    'flavor'=>'Средняя обжарка',
                    'qty'=>80,
                    'created_at'=>'2021-10-01',
                    'rating'=>2,
                ],

                [
                    'title'=>'Коста-Риканский Катурра',
                    'price'=>360,
                    'img'=>'media/images/products-seeder/costa_rican_katurra_coffee.jpg',
                    'product_type'=>2,
                    'country'=>'Коста-Рика',
                    'flavor'=>'Средняя обжарка',
                    'qty'=>90,
                    'created_at'=>'2021-09-01',
                    'rating'=>5,
                ],

                [
                    'title'=>'Тайский Сингл-Ориджин Кофе',
                    'price'=>420,
                    'img'=>'media/images/products-seeder/thai_single_origin_coffee.jpg',
                    'product_type'=>2,
                    'country'=>'Таиланд',
                    'flavor'=>'Средняя обжарка',
                    'qty'=>80,
                    'created_at'=>'2021-09-02',
                    'rating'=>4,
                ],

                [
                    'title'=>'Бразильский Арабика',
                    'price'=>280,
                    'img'=>'media/images/products-seeder/brasil_arabica.jpg',
                    'product_type'=>2,
                    'country'=>'Бразилия',
                    'flavor'=>'Средняя обжарка',
                    'qty'=>120,
                    'created_at'=>'2021-09-02',
                    'rating'=>4.5,
                ],

                [
                    'title'=>'Колумбийская Эксельсо',
                    'price'=>400,
                    'img'=>'media/images/products-seeder/colombian_excelso.jpg',
                    'product_type'=>2,
                    'country'=>'Колумбия',
                    'flavor'=>'Средняя обжарка',
                    'qty'=>100,
                    'created_at'=>'2021-09-02',
                    'rating'=>4.5,
                ],

                [
                    'title'=>'Эфиопский Иргачеффе',
                    'price'=>450,
                    'img'=>'media/images/products-seeder/ethiopian_yirgacheffe.jpg',
                    'product_type'=>2,
                    'country'=>'Эфиопия',
                    'flavor'=>'Средняя обжарка',
                    'qty'=>70,
                    'created_at'=>'2021-09-02',
                    'rating'=>4,
                ],

                [
                    'title'=>'Гватемальская Антигуа',
                    'price'=>380,
                    'img'=>'media/images/products-seeder/guatemalas_antigua.jpg',
                    'product_type'=>2,
                    'country'=>'Гватемала',
                    'flavor'=>'Средняя обжарка',
                    'qty'=>100,
                    'created_at'=>'2021-09-02',
                    'rating'=>3,
                ],

                [
                    'title'=>'Травяной чай Грейпфрут',
                    'price'=>420,
                    'img'=>'media/images/products-seeder/guatemalan_antigua.jpg',
                    'product_type'=>1,
                    'country'=>'Германия',
                    'flavor'=>'Травяной',
                    'qty'=>50,
                    'created_at'=>'2022-01-01',
                    'rating'=>5,
                ],

                [
                    'title'=>'Волшебная Африка',
                    'price'=>420,
                    'img'=>'media/images/products-seeder/magic_africa.jpg',
                    'product_type'=>1,
                    'country'=>'Россия',
                    'flavor'=>'Травяной',
                    'qty'=>70,
                    'created_at'=>'2022-01-03',
                    'rating'=>3,
                ],

                [
                    'title'=>'Мелодия трав',
                    'price'=>255,
                    'img'=>'media/images/products-seeder/melody_of_herbs.jpeg',
                    'product_type'=>1,
                    'country'=>'Россия',
                    'flavor'=>'Травяной',
                    'qty'=>200,
                    'created_at'=>'2022-01-04',
                    'rating'=>4,
                ],

                [
                    'title'=>'Чай черный Мексика',
                    'price'=>370,
                    'img'=>'media/images/products-seeder/black_tea_mexico.jpg',
                    'product_type'=>1,
                    'country'=>'Германия',
                    'flavor'=>'Черный',
                    'qty'=>20,
                    'created_at'=>'2022-01-01',
                    'rating'=>4,
                ],

                [
                    'title'=>'Время ежевики',
                    'price'=>490,
                    'img'=>'media/images/products-seeder/blackberry_time.jpeg',
                    'product_type'=>1,
                    'country'=>'Германия',
                    'flavor'=>'Черный',
                    'qty'=>550,
                    'created_at'=>'2022-01-01',
                    'rating'=>4,
                ],
            ]
            );
    }
}
